jdTrace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', RedirectView.as_view(url="/shop/"), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^user/', include('usercenter.urls')),

]

shop/urls.py
from django.conf.urls import url
from . import views
app_name = 'shop'
urlpatterns = [
    url(r'^$', views.index, name='products'),
    url(r'^(\w+)/$', views.detail, name='detail'),
]

usercenter/urls.py
from django.conf.urls import url
from . import views
app_name = "usercenter"
urlpatterns = [
    url(r'^signup/$', views.signUp, name='signup'),
    url(r'^myinterests/$', views.interstList, name='myinterests'),
    url(r'^addinterest/(\w+)/$', views.addinterst, name='addinterest'),
    url(r'^removeinterest/(\w+)/$', views.removeinterst, name='removeinterst'),

]

shop/models.py
# -*- coding: UTF-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Product(models.Model):
    """docstring for ClassName"""

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['orderNum']

    name = models.CharField(max_length=256)
    shopId = models.CharField(null=True, max_length=256)
    url = models.CharField(max_length=256)
    imgUrl = models.CharField(max_length=256)
    orderNum = models.CharField(max_length=256)
    updateTime = models.DateTimeField()


class Price(models.Model):
    """docstring for Price"""

    def __str__(self):
        return str(self.price)

    product = models.ForeignKey('shop.Product', verbose_name='对应的商品')
    price = models.FloatField()
    date = models.DateField()


class UserInterest(models.Model):
    """docstring for UserInterest"""

    def __str__(self):
        return self.user.username + self.products.name

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

usercenter/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shop/views.py
from django.shortcuts import render
from .models import Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
# Create your views here.


def index(request):
    productlist = Product.objects.all()
    paginator = Paginator(productlist, 20)

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)
    context = {
        'products': products
    }
    return render(request, 'shop/products.html', context)


def detail(request, product_id):
    product = Product.objects.get(pk=product_id)
    prices = product.price_set.all()
    jsonprices = serializers.serialize("json", prices)
    context = {
        'product': product,
        'prices': prices,
        'jsonprices': jsonprices
    }
    return render(request, 'shop/detail.html', context)

usercenter/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from shop.models import UserInterest, Product
# Create your views here.


def signUp(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return render(request, "registration/login.html")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})


@login_required()
def interstList(request):
    user = request.user
    interests = UserInterest.objects.filter(user=user)
    return render(request, "usercenter/myinterest.html",
                  {'interests': interests})


@login_required()
def addinterst(request, productId):
    user = request.user
    if UserInterest.objects.filter(user=user,
                                   product_id=productId).count() == 0:
        userInterest = UserInterest()
        userInterest.user = user
        userInterest.product = Product.objects.get(pk=productId)
        userInterest.save()
    return redirect('usercenter:myinterests')


@login_required()
def removeinterst(request, productId):
    user = request.user
    UserInterest.objects.filter(user=user,
                                product_id=productId).delete()
    return redirect('usercenter:myinterests')

shop/templates/shop/detail.html
{% extends 'base.html' %} {% load staticfiles %} 
{% block csscontent%}
<link rel="stylesheet" type="text/css" href="{% static 'css/lib/morris.css' %}">
{% endblock%}d  
{% block maincontent %}
<div class="content">
    <!-- settings changer -->
    <div class="skins-nav">
        <a href="#" class="skin first_nav selected">
            <span class="icon"></span><span class="text">Default</span>
        </a>
        <a href="#" class="skin second_nav" data-file="{% static 'css/skins/dark.css' %}">
            <span class="icon"></span><span class="text">Dark skin</span>
        </a>
    </div>
    <div class="container-fluid">
        <div id="pad-wrapper" class="user-profile">
            <!-- header -->
            <div class="row-fluid header">
                <div class="span8">
                    <img src='{{product.imgUrl}}' class="avatar" />
                    <h3 class="name">{{product.name}}</h3>
                </div>
            </div>
            <div class="row-fluid profile">
                <!-- bio, new note & orders column -->
                <div class="span9 bio">
                    <div class="profile-box">
                        <!-- biography -->
                        <div class="span12 section">
                            <h5>商品简介</h5>
                            <p><a href="{{product.url}}" target="_blank">官网查看详情</a></p>
                        </div>
                        <!-- new comment form -->
                        <div class="section">
                            <h5>是否感兴趣？</h5>
                            <p>关注一下，更方便查看哦</p>
                            <div class="span12 submit-box pull-right">
                                <a href="{% url 'usercenter:addinterest' product.id %}" class="btn-glow primary">关注</a>
                            </div>
                        </div>
                        <h6>价格追踪</h6>
                        <br />
                        <div id="linechart" class="span12" style="height: 300px;">
                        </div>
                        <br>
                        <!-- recent orders table -->
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="span2">
                                        价格ID
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span> 获取日期
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span> 价格
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span> 操作
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for price in prices %}
                                <!-- row -->
                                <tr>
                                    <td>
                                        <a href="#">#{{price.id}}</a>
                                    </td>
                                    <td>
                                        {{price.date|date:"Y-m-d"}}
                                    </td>
                                    <td>
                                        ￥{{price.price}}
                                    </td>
                                    <td>
                                        无
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block jscontent %}
<script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src='{% static "js/morris.min.js" %}'></script>
<script type="text/javascript">
$(document).ready(function() {
    var data = {{jsonprices | safe}};
    var mydata = [];
    for (var i = 0; i < data.length; i++) {
        mydata[i]=data[i].fields;
    }
    new Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'linechart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: mydata,
        // The name of the data record attribute that contains x-values.
        xkey: 'date',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['price'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['价格'],
        smooth:false
    });
});
</script>
{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block maincontent%}
   <div class="content">
        
        <!-- settings changer -->
        <div class="skins-nav">
            <a href="#" class="skin first_nav selected">
                <span class="icon"></span><span class="text">Default</span>
            </a>
            <a href="#" class="skin second_nav" data-file="{% static 'css/skins/dark.css' %}">
                <span class="icon"></span><span class="text">Dark skin</span>
            </a>
        </div>
        
        <div class="container-fluid">
            <div id="pad-wrapper" class="users-list">
                <div class="row-fluid header">
                    <h3>商品列表</h3>
                    </div>
                </div>

                <!-- Users table -->
                <div class="row-fluid table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span4 sortable">
                                    商品名称
                                </th>
                                <th class="span3 sortable">
                                    <span class="line"></span>数据更新时间
                                </th>
                                <th class="span2 sortable">
                                    <span class="line"></span>数据编号
                                </th>
                                <th class="span3 sortable align-right">
                                    <span class="line"></span>商品来源
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                     
                        {% for product in products %}
                        <!-- row -->
                        <tr>
                            <td>
                                <a href="{% url 'shop:detail' product.id %}" target="_blank" class="name">{{product.name}}</a>
                            </td>
                            <td>
                                {{product.updateTime|date:'Y-m-d H:m:s'}}
                            </td>
                            <td>
                                {{product.orderNum}}
                            </td>
                            <td class="align-right">
                                <a href="{{product.url}}">商品来源</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination pull-right">
                    <ul>
                    {% if products.has_previous %}
                        <li><a href="{%url 'shop:products' %}?page={{ products.previous_page_number }}">&#8249;</a></li>
                    {% endif %}
                       
                        <li><span class="active" href="#">第 {{ products.number }}页，共  {{ products.paginator.num_pages }}页</span></li>
                        


        {% if products.has_next %}
            <li><a href="{%url 'shop:products' %}?page={{ products.next_page_number }}">&#8250;</a></li>
        {% endif %}

                    </ul>
                </div>
                <!-- end users table -->
            </div>
        </div>
    </div>

    {% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Detail Admin - User list</title>
    {% include "base_css.html" %}
    {% block csscontent%}{% endblock %}
</head>
<body>

    <!-- navbar -->
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <button type="button" class="btn btn-navbar visible-phone" id="menu-toggler">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <a class="brand" href="{% url 'index'%}"><img src='{% static "img/logo.png" %}'  /></a>

            <ul class="nav pull-right">                
  
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle hidden-phone" data-toggle="dropdown">
                        {{user.username}}
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'usercenter:myinterests'%}">我的关注</a></li>
                        <li><a href="{% url 'logout'%}">退出登录</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="settings hidden-phone">
                    <a href="{%url 'login'%}" role="button">
                        登录
                    </a>
                </li>
                {% endif %}
            </ul>            
        </div>
    </div>
    <!-- end navbar -->

    <!-- sidebar -->
    <div id="sidebar-nav">
        <ul id="dashboard-menu">
            <li>                
                <a class="dropdown-toggle" href="#">
                    <i class="icon-home"></i>
                    <span>个人中心</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="{% url 'usercenter:myinterests'%}">我的关注</a></li>
                </ul>
            </li>            
             <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-group"></i>
                    <span>商品</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="{% url 'shop:products'%}">商品列表</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- end sidebar -->
    

	<!-- main container -->
    {% block maincontent %}maincontent {% endblock %}
    <!-- end main container -->
    {% include "base_js.html" %}

    {% block jscontent%}<!--页面自己的js--> {%endblock%}


</body>
</html>

templates/base_css.html
	{% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
    <!-- bootstrap -->
    <link href='{% static "css/bootstrap/bootstrap.css" %}'  rel="stylesheet" />
    <link href='{% static "css/bootstrap/bootstrap-responsive.css" %}'  rel="stylesheet" />
    <link href='{% static "css/bootstrap/bootstrap-overrides.css" %}'  type="text/css" rel="stylesheet" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href='{% static "css/layout.css" %}'  />
    <link rel="stylesheet" type="text/css" href='{% static "css/elements.css" %}'  />
    <link rel="stylesheet" type="text/css" href='{% static "css/icons.css" %}'  />

    <!-- libraries -->
    <link href='{% static "css/lib/font-awesome.css" %}'  type="text/css" rel="stylesheet" />
    
    <!-- this page specific styles -->
    <link rel="stylesheet" href='{% static "css/compiled/user-list.css" %}'  type="text/css" media="screen" />

    <!-- open sans font -->
    <link href='http://fonts.useso.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css' />

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

templates/base_js.html
	{% load staticfiles %}
	<!-- scripts -->
    <script src='{% static "js/jquery-latest.js" %}' ></script>
    <script src='{% static "js/bootstrap.min.js" %}' ></script>
    <script src='{% static "js/theme.js" %}' ></script>
    <script type="text/javascript">
    	$(document).ready(function(){

    		var pathname = window.location.pathname;
    		var theHref = $.find("#sidebar-nav a[href='"+pathname+"']")[0];
    		$(theHref).addClass("active");
    		$(theHref).closest("ul").addClass("active");
    		$(theHref).closest("ul").parent("li").addClass("active").prepend('<div \
                class="pointer">\
                    <div class="arrow"></div>\
                    <div class="arrow_border"></div>\
                </div>');
    	});
    </script>

usercenter/templates/usercenter/myinterest.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block maincontent%}
   <div class="content">
        
        <!-- settings changer -->
        <div class="skins-nav">
            <a href="#" class="skin first_nav selected">
                <span class="icon"></span><span class="text">Default</span>
            </a>
            <a href="#" class="skin second_nav" data-file="{% static 'css/skins/dark.css' %}">
                <span class="icon"></span><span class="text">Dark skin</span>
            </a>
        </div>
        
        <div class="container-fluid">
            <div id="pad-wrapper" class="users-list">

                <!-- Users table -->
                <div class="row-fluid table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span6 sortable">
                                    商品名称
                                </th>
                                <th class="span6 sortable">
                                    <span class="line"></span>操作
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                     
                        {% for interest in interests %}
                        <!-- row -->
                        <tr>
                            <td>
                                <a href="{% url 'shop:detail' interest.product.id %}" target="_blank" class="name">{{interest.product.name}}</a>
                            </td>
                            <td>
                                <a href="{% url 'usercenter:removeinterst' interest.product.id %}" class="btn-glow primary">取消关注</a>
                            </td>

                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- end users table -->
            </div>
        </div>
    </div>

    {% endblock %}